prakhar/Storage_Dashboard/Storage_Dashboard/apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

prakhar/Storage_Dashboard/Storage_Dashboard/apps/home/routes.py
import pymysql
# from tables import Results
from flask_table import Table, Col, LinkCol
# from db_config import MySQL
from flaskext.mysql import MySQL
from flask import flash, render_template, request, redirect
from flask import Flask
from apps import new_db
import os
import subprocess

from apps.home import blueprint
from flask import render_template, request, url_for, session
from flask_login import login_required
from jinja2 import TemplateNotFound
import pandas as pd
import os
from werkzeug.utils import secure_filename
import mysql.connector as mysql
from mysql.connector import Error
 

class Results(Table):
    user_id = Col('Id', show=False)
    user_name = Col('Name')
    user_login = Col('Login')
    user_onboarded = Col('Onboarded')
    user_dept = Col('Department')
    # delete = LinkCol('Delete', 'delete_user', url_kwargs=dict(id='user_id'))



@blueprint.route('/index')
@login_required
def index():
    print("home dir")
    # os.system("pwd > test.txt")
    results = subprocess.run(['/root/my_script.sh'], stdout=subprocess.PIPE).stdout.decode('utf-8')
    result_set = results.split("\n")[2:]
    print(result_set)
    storage_data=dict()
    users_dir=[]
    for item in result_set:
        if item not in ['', "/home/\r"]:
            storage, userName = item[:-1].split("\t")
            if userName.split("/")[2] !='':
                if userName.split("/")[2] not in storage_data.keys():
                    storage_data[userName.split("/")[2]] = storage
                # users_dir.append(userName.split("/")[2])
    print(storage_data)
    print(users_dir)

    department_storage = dict()
    conn = None
    cursor = None
    try:
        conn = new_db.connect()
        cursor = conn.cursor(pymysql.cursors.DictCursor)
        cursor.execute("SELECT user_login, user_dept FROM users")
        rows = cursor.fetchall()
        print(rows)
        for row in rows:
            usr, dept = row['user_login'], row['user_dept']
            if dept not in department_storage.keys():
                department_storage[dept] = storage_data[usr]
            else:
                department_storage[dept] = department_storage[dept] + storage_data[usr]
        for key, value in department_storage.items():
            print(key, value)
        
        



    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()
    print("over")


    return render_template('home/index.html', segment='index')

@blueprint.route('/users.html')
@login_required
def users():
    # print("\n\n in db users \n\n")
    conn = None
    cursor = None
    try:
        conn = new_db.connect()
        cursor = conn.cursor(pymysql.cursors.DictCursor)
        cursor.execute("SELECT * FROM users")
        rows = cursor.fetchall()
        print(rows)
        # table = Results(rows)
        # table.border = Tru
        print(rows)
        return render_template('home/users.html', segment='users', value=rows)
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()


@blueprint.route('/<template>')
@login_required
def route_template(template):

    try:

        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)
        print("\n\n segment check \n\n" + segment)

        # Serve the file (if exists) from app/templates/home/FILE.html
        if template != 'users.html': 
            return render_template("home/" + template, segment=segment)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500


# Helper - Extract current page name from request
def get_segment(request):

    try:

        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment

    except:
        return None

@blueprint.route('/new_user')
@login_required
def add_user_view():
    return render_template('home/add_user.html', segment='add_user')


@blueprint.route('/add', methods=['POST'])
@login_required
def add_user():
    print(" ################ in add user form function")
    conn = None
    cursor = None
    try:
        _name = request.form['inputName']
        _login = request.form['inputLogin']
        _onboarded = request.form['inputOnboarded']
        _department = request.form['inputDepartment']
        # validate the received values
        if _name and _login and _onboarded and _department and request.method == 'POST':
            # save edits
            # print("################before executing sql")

            sql = "INSERT INTO users (user_name, user_login, user_onboarded, user_dept) VALUES(%s, %s, %s, %s)"
            data = (_name, _login, _onboarded, _department)
            conn = new_db.connect()
            cursor = conn.cursor()
            cursor.execute(sql, data)
            conn.commit()

            cursor.execute("SELECT * FROM users")
            rows = cursor.fetchall()
            # print(' ################ User added successfully!')
            return redirect(url_for('home_blueprint.users'))
        else:
            return 'Error while adding user'
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()


@blueprint.route('/delete/<int:id>')
@login_required
def delete_user(id):
    conn = None
    cursor = None
    try:
        conn = new_db.connect()
        cursor = conn.cursor()
        cursor.execute("DELETE FROM users WHERE user_id=%s", (id,))
        conn.commit()
        flash('User deleted successfully!')
        return redirect(url_for('home_blueprint.users'))
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()

@blueprint.route('/bulk_add', methods=['POST'])
@login_required
def bulk_add_users():
    print(" ################ in bulk add user form function")
    
    UPLOAD_FOLDER = os.path.join('/root/project/TAP-2022-Team-2-EE-Big-Build-Assessment/prakhar/Storage_Dashboard/Storage_Dashboard/apps/static', 'uploads')
    print(UPLOAD_FOLDER)
    ALLOWED_EXTENSIONS = {'csv'}
    try:
        if request.method == 'POST':
            uploaded_df = request.files['uploaded-file']
            # Extracting uploaded data file name
            print(uploaded_df)
            data_filename = secure_filename(uploaded_df.filename)
    
            # flask upload file to database (defined uploaded folder in static path)
            uploaded_df.save(os.path.join(UPLOAD_FOLDER, data_filename))

            loadData(os.path.join(UPLOAD_FOLDER, data_filename))
            return redirect(url_for('home_blueprint.users'))
        else:
            print("Error in uploading Data")

    except Exception as e:
        print(e)
    finally:
        print("END")
        

def loadData(data_file_path):
    conn = None
    cursor = None 
    # read csv file in python flask (reading uploaded csv file from uploaded server location)
    uploaded_df = pd.read_csv(data_file_path)

    # change fromat of date
    uploaded_df['onboarded'] = uploaded_df['onboarded'].apply(lambda x : formatDate(x))

    try:
        conn = mysql.connect(host='localhost', database='USERMGT', user='root', password='Root@123')
        if conn.is_connected():
            cursor = conn.cursor()
            cursor.execute("select database();")
            record = cursor.fetchone()
            print("You're connected to database: ", record)

            for i,row in uploaded_df.iterrows():
                sql = "INSERT INTO USERMGT.users (user_name, user_login, user_onboarded, user_dept) VALUES (%s,%s,%s,%s);"
                cursor.execute(sql, tuple(row))
                print("Record inserted")
                conn.commit()
    except Error as e:
                print("Error while connecting to MySQL", e)
    finally:
        cursor.close()
        conn.close()


def formatDate(date_ddmmyyyy):
    date_dd, date_mm, date_yyyy = date_ddmmyyyy.split("/")
    return date_yyyy+date_mm+date_dd

prakhar/Storage_Dashboard/Storage_Dashboard/apps/templates/home/add_user-no.html
{% extends "layouts/base.html" %}

{% block title %} User Profile {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<title>Add User</title>
<div>
    <h2>Add User</h2>
    <form method="post" action="/add">
        <dl>
            <p>
            <input name="inputName" value="" type="text"
                        placeholder="Name" autocomplete="off" required>
            </p>
            <p>
            <input name="inputLogin" value="" type="text"
                        placeholder="Login" autocomplete="off" required>
            </p>
            <p>
            <input name="inputOnboarded" value="" type="date"
                        placeholder="Onboarded" autocomplete="off" required>
            </p>
            <input name="inputDepartment" value="" type="text"
                        placeholder="Department" autocomplete="off" required>
            </p>
        </dl>
        <p>
        <input type="submit" value="Submit">
        </p>
    </form>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

prakhar/Storage_Dashboard/Storage_Dashboard/apps/templates/home/bulk_upload.html
{% extends "layouts/base.html" %}

{% block title %} All Users {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


<div class="content">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h3 class="title">Upload from CSV file</h3>
        </div>

        <div class="card-body">
          <form method="post" action="/bulk_add" enctype="multipart/form-data">

            <div class="row">

              <div class="col-md-6 pr-md-1">
                  <input type="file" name="uploaded-file" accept=".csv"  placeholder="Upload your CSV file here" required>

              </div>
              </div>
            
            <div class="card-footer">
              <input class= "btn btn-fill btn-primary" type="submit" value="Upload Data">
            </div>
          </form>
        </div>
      </div>
    </div>
    
  </div>
</div>




{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

prakhar/Storage_Dashboard/Storage_Dashboard/apps/templates/home/index.html
{% extends "layouts/base.html" %}

{% block title %} Storage Monitoring Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card card-chart">
                <div class="card-header ">
                    <div class="row">
                        <!-- <input type="file" name="readfile" id="readfile" /> -->
                        <div class="col-sm-6 text-left">
                            <h3 class="card-category">Total Storage Used by your Department</h3>
                            <h2 class="card-title">Storage Used by IT Department</h2>
                        </div>
                        <div class="col-sm-6">
                            <div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
                                <label class="btn btn-sm btn-primary btn-simple active" id="0">
                                    <input type="radio" name="options" checked>
                                    <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block">IN GB</span>
                                    <span class="d-block d-sm-none">
                    <i class="tim-icons icon-single-02"></i>
                </span>
                                </label>
                                <label class="btn btn-sm btn-primary btn-simple" id="1">
                                    <input type="radio" class="d-none d-sm-none" name="options">
                                    <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block">In Percentage</span>
                                  
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="chartBig1"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row" hidden>
        <div class="col-lg-4">
            <div class="card card-chart">
                <div class="card-header">
                    <h5 class="card-category">Storage Used Today</h5>
                    <h3 class="card-title"><i class="tim-icons icon-bell-55 text-primary"></i> 763 MB</h3>
                </div>
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="chartLinePurple"></canvas>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card card-chart">
                <div class="card-header">
                    <h5 class="card-category">Storage Used this Week</h5>
                    <h3 class="card-title"><i class="tim-icons icon-delivery-fast text-info"></i> 1589 MB</h3>
                </div>
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="CountryChart"></canvas>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card card-chart">
                <div class="card-header">
                    <h5 class="card-category">Storage Used this Month</h5>
                    <h3 class="card-title"><i class="tim-icons icon-send text-success"></i> 17530 MB</h3>
                </div>
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="chartLineGreen"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script>
     gradientBarChartConfiguration = {
      maintainAspectRatio: false,
      legend: {
        display: false
      },

      tooltips: {
        backgroundColor: '#f5f5f5',
        titleFontColor: '#333',
        bodyFontColor: '#666',
        bodySpacing: 4,
        xPadding: 12,
        mode: "nearest",
        intersect: 0,
        position: "nearest"
      },
      responsive: true,
      scales: {
        yAxes: [{

          gridLines: {
            drawBorder: false,
            color: 'rgba(29,140,248,0.1)',
            zeroLineColor: "transparent",
            steps : 5,
            stepValue : 5,
            max : 100
          },
          ticks: {
            suggestedMin: 0,
            suggestedMax: 50,
            padding: 20,
            fontColor: "#9e9e9e"
          }
        }],

        xAxes: [{

          gridLines: {
            drawBorder: false,
            color: 'rgba(29,140,248,0.1)',
            zeroLineColor: "transparent",
          },
          ticks: {
            padding: 20,
            fontColor: "#9e9e9e"
          }
        }]
      }
    };

    var chart_labels = ['ADARSH', 'ENG', 'SALES', 'HR', 'MGT', 'FIN', 'SAHAJ'];
    var chart_data = [100,39,41,138,10,32,41,48,38];


    var ctx = document.getElementById("chartBig1").getContext('2d');

    var gradientStroke = ctx.createLinearGradient(0, 230, 0, 50);


    gradientStroke.addColorStop(1, 'rgba(29,140,248,0.2)');
    gradientStroke.addColorStop(0.4, 'rgba(29,140,248,0.0)');
    gradientStroke.addColorStop(0, 'rgba(29,140,248,0)'); //blue colors


    var config = {
      type: 'bar',
      responsive: true,
      legend: {
        display: false
      },
      data: {
        labels: chart_labels,
        datasets: [{
          label: "Storage used by Department in GB / % ",
          fill: true,
          value : chart_data,
          backgroundColor: gradientStroke,
          hoverBackgroundColor: gradientStroke,
          borderColor: '#1f8ef1',
          borderWidth: 2,
          borderDash: [],
          borderDashOffset: 0.0,
          data: chart_data,
        }]
      },
      options: gradientBarChartConfiguration
    };
    var myChartData = new Chart(ctx, config);
    $("#0").click(function() {
      var data = myChartData.config.data;
      data.datasets[0].data = chart_data;
      data.labels = chart_labels;
      myChartData.update();
    });
    $("#1").click(function() {
      var chart_data = [94,80,87,85,32,62,51,90,60];
      var data = myChartData.config.data;
      data.datasets[0].data = chart_data;
      data.labels = chart_labels;
      myChartData.update();
    });

    // $("#2").click(function() {
    //   var chart_data = [60, 80, 65, 130, 80, 105, 90, 130, 70, 115, 60, 130];
    //   var data = myChartData.config.data;
    //   data.datasets[0].data = chart_data;
    //   data.labels = chart_labels;
    //   myChartData.update();
    // });

    // $(document).ready(function () {
    //     // Javascript method's body can be found in assets/js/demos.js
    //     demo.initDashboardPageCharts();

    // });
</script>

{% endblock javascripts %}

prakhar/Storage_Dashboard/Storage_Dashboard/apps/templates/home/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h4 class="title">Login to CT ADMIN</h4>
                        </div>
                        <div class="card-body px-5 py-3">
                            <form>
                                <div class="row">
                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Username</label>
                                            <input type="text" class="form-control" placeholder="Username"
                                                    value="michael23">
                                        </div>
                                    </div>

                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" class="form-control" placeholder="password"
                                                    value="example@gmail.com">
                                        </div>
                                    </div>
                                </div>

                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-fill btn-primary">Login</button>
                            
                            <br /><br />

                            <p>
                                Don't have an account? <a href="/register.html" class="text-primary">Register</a>                            
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

prakhar/Storage_Dashboard/Storage_Dashboard/apps/templates/home/notifications.html
{% extends "layouts/base.html" %}

{% block title %} Notifications {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <h1>Adarsh</h1>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

prakhar/Storage_Dashboard/Storage_Dashboard/apps/templates/home/page-404.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h3 class="title">
                                Error 404
                            </h3>
                        </div>
                        <div class="card-body px-2 py-2">

                            <p class="text-center">
                                Page not found - Please contact support.
                            </p>

                        </div>
                        <div class="card-footer text-center">
                            <a href="/" class="btn btn-fill btn-primary">HOME</a>
                            
                            <br /><br />

                            <p>
                                Get <a href="#" class="text-primary">Support</a>                            
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

prakhar/Storage_Dashboard/Storage_Dashboard/apps/templates/home/page-500.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 500 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h3 class="title">
                                Error 500
                            </h3>
                        </div>
                        <div class="card-body px-2 py-2">

                            <p class="text-center">
                                Server ERROR - Please contact support.
                            </p>

                        </div>
                        <div class="card-footer text-center">
                            <a href="/" class="btn btn-fill btn-primary">HOME</a>
                            
                            <br /><br />

                            <p>
                                Get <a href="#" class="text-primary">Support</a>                            
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

prakhar/Storage_Dashboard/Storage_Dashboard/apps/templates/home/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container">
            <div class="row pt-5">
                <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-header text-center py-4">
                            <h4 class="title">
                                Sign UP
                            </h4>
                        </div>
                        <div class="card-body px-5 py-3">
                            <form>
                                <div class="row">
                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Username</label>
                                            <input type="text" class="form-control" placeholder="Username"
                                                    value="michael23">
                                        </div>
                                    </div>

                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input type="email" class="form-control" placeholder="email"
                                                    value="example@gmail.com">
                                        </div>
                                    </div>

                                    <div class="col-md-12 px-md-1">
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" class="form-control" placeholder="password"
                                                    value="example@gmail.com">
                                        </div>
                                    </div>
                                </div>

                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-fill btn-primary">Register</button>

                            <br /><br />
                            
                            <p>
                                Have an account? <a href="/login.html" class="text-primary">Login</a>
                            </p> 
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

prakhar/Storage_Dashboard/Storage_Dashboard/apps/templates/home/users.html
{% extends "layouts/base.html" %}

{% block title %} All Users {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

{{ table }} 
<div class="content">
    <div class="row">
      <div class="col-md-12">
        <div class="card ">
          <div class="card-header">
            <h4 class="card-title"> Users </h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table tablesorter " id="">
                <thead class=" text-primary">
                  <tr>
                    <th>
                      Name
                    </th>
                    <th>
                      Login ID
                    </th>
                    <th>
                      Onboarding Date
                    </th>
                    <th>
                      Department
                    </th>
                    <th>
                      Storage Utilisation
                    </th>
                    <th class="text-center">
                        Delete User
                      </th>
                  </tr>
                </thead>
                <tbody>
                    {% for row in value %}
                    <tr>
                        <td>
                          {{row['user_name']}}
                        </td>
                        <td>
                            {{row['user_login']}}
                        </td>
                        <td>
                            {{row['user_onboarded']}}
                        </td>
                        <td class="text-center">
                            {{row['user_dept']}}
                        </td>
                        <td class="text-center">
                          ##/##
                      </td>
                        <td>
                            <a href="{{ url_for('home_blueprint.delete_user', id=row['user_id']) }}">Delete</a>
                            
                        </td>
                      </tr>
                    {% endfor %}

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}